# Generated by Django 4.1.7 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=20)),
                ('date_updated', models.DateField()),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
